server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
  servlet:
    context-path: /vouchers
spring:
  application:
    name: ms-pool-vouchers
  data:
    mongodb:
      uri: mongodb://localhost:37017/vouchers
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:8080/vouchers/oauth2/introspect
          client-id: voucher-backend
          client-secret: maria

springdoc:
  packagesToScan: br.com.pool.vouchers.api.entrypoint
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    tagsSorter: alpha

voucher:
  auth:
    provider-url: http://localhost:8080/vouchers/oauth2/token

